repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      # - id: no-commit-to-branch
      #   name: Don't commit to master
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.8
    hooks:
        # Run the linter.
        - id: ruff
          args: [ '--select', 'I001', '--fix' ]
        # Run the formatter.
        - id: ruff-format
