---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

##############################################################
# Trigger on Pull Request events (open, reopen, synchronize) #
##############################################################
on:
  pull_request:
    branches:
      - 'master'
      - 'v2'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v6
        env:
          FILTER_REGEX_EXCLUDE: (test_.*.py)
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: false
          VALIDATE_PYTHON_ISORT: false

      ###################################
      # Run pre-commit against codebase #
      ###################################
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - run: |
            pip install pre-commit
            sudo chown -R "$(id -u):$(id -g)" .
            pre-commit run --from-ref v2 --to-ref HEAD
